# Database
quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.database.generation=update
quarkus.datasource.devservices.port=5432

# OpenAPI/Swagger
quarkus.smallrye-openapi.path=/swagger-ui
quarkus.swagger-ui.always-include=true

# Health Checks
quarkus.smallrye-health.root-path=/health

# JWT - solo habilitar en prod
%dev.quarkus.smallrye-jwt.enabled=false
%test.quarkus.smallrye-jwt.enabled=false

# Logging
quarkus.log.level=INFO
quarkus.log.category."com.david".level=DEBUG
quarkus.log.category."org.hibernate.SQL".level=DEBUG
quarkus.log.category."org.hibernate.orm.jdbc.bind".level=TRACE
